### ISSUE TITLE
判定結果のフォーマット変更

### ISSUE THREAD

**Issue by teamhanzo01** [Demo20170623/DummySystem#2]
今の仕様だと、"Fizz", "Buzz", "FizzBuzz"しか出力されません。
判定した数値も一緒に出力してください。

**Comment by HanzoHatt0ri** [comment]
了解しました。
出力方法は以下の通りでよろしいでしょうか？
　"<number> is Fizz or Buzz or FizzBuzz"

**Comment by teamhanzo01** [comment]
はい。そのフォーマットでお願いします。

**Comment by HanzoHatt0ri** [comment]
完了しました。
プルリクエストは#3です。

**Comment by teamhanzo01** [comment]
ありがとうございました！
Issueを閉じますね。
